version: '3.1'

services:
    app:
        build: .
        container_name: 'php'
        depends_on:
            - rabbitmq
        volumes:
            - ./:/app
        env_file:
            - .env
        ports:
            - 8081:80
        networks:
            - stack
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: interview_rabbit
        restart: on-failure
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=password
            - RABBITMQ_DEFAULT_VHOST=vhost
        ports:
            - "127.0.0.1:5672:5672"
            - "15672:15672"
        networks:
            - stack
networks:
    stack:
        name: stack

volumes:
    interview_rabbit:
